### ISSUE TITLE
The callback decrypt() exists in module aescrypto, but only one callback may be registered to a function in a native module.

### ISSUE THREAD

**Issue by luolin2611** [rocwangv/react-native-aes-kit#3]
Hi，I checked the cause again for the following questions.
![image](https://user-images.githubusercontent.com/17327008/40903692-da22632a-680a-11e8-8452-ca547495ee8f.png)
The callback decrypt() exists in module aescrypto, but only one callback may be registered to a function in a native module.

Find out why, when the server encryption data volume is relatively large, the Android side can properly decrypt the iOS side such as the error, how to solve it?

Decrypted string reference text     [new_text.txt](https://github.com/rocwangv/react-native-aes-kit/files/2070764/new_text.txt)

secretKey = '0102030405060708'
const iv = '1112131415161718'

Thank you.

**Comment by luolin2611** [comment]
When the amount of data is large, the encrypted strings in the Java project can be decrypted at the Android end, and the error is reported on the IOS side.
I saw Chinese annotation inside code, can add QQ to solve online, problem is urgent, thank. QQ: 3014418409. Thank you!

**Comment by rocwong-cn** [comment]
My **LARGE** data :[164912-len.txt](https://github.com/rocwangv/react-native-aes-kit/files/2075916/164912-len.txt)
I have  successful decrypted the data that it's length is 164912 , and your data is just 20288 .

So , this issue is not caused by data size ,maybe you can check your plaintext's format 、encoding .....

BTW , I've added your QQ : )
